jenkins:
  systemMessage: "Jenkins Controller — лаборатория, поднята через Terraform + JCasC"
  numExecutors: 0

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "${JENKINS_ADMIN_PASSWORD}"

  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
