credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "agent-ssh-key"
              username: "adminuser"
              description: "SSH Private Key for Agent"
              privateKeySource:
                directEntry:
                  privateKey: |
                    ${indent(6, jenkins_agent_private_key)}

jenkins:
  systemMessage: "Jenkins Controller — лаборатория, поднята через Terraform + JCasC"
  numExecutors: 0
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "$${JENKINS_ADMIN_PASSWORD}"

  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"

  nodes:
    - permanent:
        name: "agent-01"
        remoteFS: "/home/adminuser/jenkins"
        numExecutors: 2
        labelString: "linux docker"
        launcher:
          ssh:
            host: "10.0.1.22"
            port: 22
            credentialsId: "agent-ssh-key"
            launchTimeoutSeconds: 60
            maxNumRetries: 3
            retryWaitTime: 15
            tcpNoDelay: true
