name: DEPLOY - API

on:
    push:
        branches: [main]
        paths:
            - 'services/api/**'
    workflow_dispatch:
        inputs:
            environment:
                description: 'Deployment environment'
                required: true
                default: 'dev'
                type: choice
                options:
                    - dev
                    - staging
                    - prod
            force_deploy:
                description: 'Force deployment even if no changes detected'
                required: true
                default: false
                type: boolean

permissions:
    id-token: write
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - uses: ./.github/actions/setup-node-cached
              with:
                  node-version: '20'
                  working-directory: 'services/api'

            - name: Build API
              run: npm run build
              working-directory: 'services/api'

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: api-build
                  path: services/api/dist
                  overwrite: true
                  compression-level: 1

            - name: Set tag
              id: set_tag
              run: echo "image_tag=sha-${{ github.sha }}" >> $GITHUB_OUTPUT

        outputs:
            image_tag: ${{ steps.set_tag.outputs.image_tag }}

    build-image:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: api-build

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4
            - name: Build and push Docker image to GitHub Container Registry
              uses: docker/build-push-action@v7
              with:
                  push: true
                  tags: ghcr.io/my-api:${{ needs.build.outputs.image_tag }}

    deploy-dev:
        runs-on: ubuntu-latest
        needs: build-image
        environment:
            name: dev
        if: inputs.environment == 'dev' || github.event_name == 'push'
        steps:
            - name: Display image tag
              run: echo "We are deploying the image with tag ${{needs.build.outputs.image_tag}} to the dev environment."

            - name: Azure Login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: api-build
    deploy-staging:
        runs-on: ubuntu-latest
        needs: build-image
        environment:
            name: staging
        if: inputs.environment == 'staging'
        steps:
            - name: Azure Login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: api-build

    deploy-prod:
        runs-on: ubuntu-latest
        needs: build-image
        environment:
            name: prod
        if: inputs.environment == 'prod'
        steps:
            - name: Azure Login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: api-build
